[colors]

ansi = [
    '#073642',
    '#dc322f',
    '#859900',
    '#b58900',
    '#268bd2',
    '#d33682',
    '#2aa198',
    '#eee8d5',
]

brights = [
    '#002b36',
    '#cb4b16',
    '#586e75',
    '#657b83',
    '#839496',
    '#6c71c4',
    '#93a1a1',
    '#fdf6e3',
]
cursor_bg = '#586e75'
cursor_border = '#586e75'
cursor_fg = '#93a1a1'

background = '#002b36'
foreground = '#657b83'

[colors.indexed]

[metadata]
name = 'Solarized'
